version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Внешний:Внутренний
      - "5432:5432"
    volumes:
      # Сохраняет данные базы на вашем компьютере, чтобы они не пропали при удалении контейнера
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"

  app:
    # Docker будет искать Dockerfile в текущей папке и соберет образ приложения
    build: .
    # *** ИСПРАВЛЕННАЯ КОМАНДА ЗАПУСКА ***
    command: sh -c "sh wait-for.sh db:5432 redis:6379 -- uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      # Монтирует код с вашего компьютера внутрь контейнера для горячей перезагрузки (при --reload)
      - .:/app
    env_file:
      # Использует ваш локальный .env файл для переменных окружения
      - .env
    depends_on:
      # Гарантирует, что база и Redis запустятся раньше приложения Python
      - db
      - redis

volumes:
  db_data:
